version: '3'

services:
  pg:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=kl
      - POSTGRES_USER=kl
      - POSTGRES_PASSWORD=kl
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    environment:
      - ADMINER_DEFAULT_SERVER=pg
    depends_on:
      - pg
